// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using home_backend.Models;

namespace home_backend.Migrations
{
    [DbContext(typeof(LinkContext))]
    [Migration("20200904203618_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Link", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Url")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "gmail 1",
                            Type = "cloud",
                            Url = "https://mail.google.com/mail/u/0/#inbox"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "gmail 2",
                            Type = "cloud",
                            Url = "https://mail.google.com/mail/u/1/#inbox"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "gdrive",
                            Type = "cloud",
                            Url = "https://drive.google.com/drive/u/0/"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "gphotos",
                            Type = "cloud",
                            Url = "https://photos.google.com/?hl=es"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "youtube",
                            Type = "social",
                            Url = "https://www.youtube.com/"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "reddit",
                            Type = "social",
                            Url = "https://www.reddit.com/"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "twitch",
                            Type = "social",
                            Url = "https://www.twitch.tv/directory"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "twitter",
                            Type = "social",
                            Url = "https://www.twitter.com/"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "whatsapp",
                            Type = "social",
                            Url = "https://web.whatsapp.com/"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "fake email",
                            Type = "pirating",
                            Url = "https://temp-mail.org/"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "nyaa",
                            Type = "pirating",
                            Url = "https://nyaa.si/"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "rarbg",
                            Type = "pirating",
                            Url = "https://rargb.to/"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "fitgirl",
                            Type = "pirating",
                            Url = "http://fitgirl-repacks.site/"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "cs.rin.ru",
                            Type = "pirating",
                            Url = "https://cs.rin.ru"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "drive bypass",
                            Type = "pirating",
                            Url = "https://gdbypass.host/"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "r/piracy",
                            Type = "pirating",
                            Url = "https://www.reddit.com/r/Piracy/wiki/megathread"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "github",
                            Type = "services",
                            Url = "https://github.com/"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "bitbucket",
                            Type = "services",
                            Url = "https://bitbucket.com/"
                        },
                        new
                        {
                            Id = 19L,
                            Name = "gmaps",
                            Type = "services",
                            Url = "https://www.google.com/maps"
                        },
                        new
                        {
                            Id = 20L,
                            Name = "wetransfer",
                            Type = "services",
                            Url = "https://wetransfer.com/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
