// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using home.Data;

namespace home.Migrations
{
    [DbContext(typeof(HomeContext))]
    partial class HomeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("home.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "gmail 1",
                            Type = "cloud",
                            Url = "https://mail.google.com/mail/u/0/#inbox"
                        },
                        new
                        {
                            Id = 2,
                            Name = "gmail 2",
                            Type = "cloud",
                            Url = "https://mail.google.com/mail/u/1/#inbox"
                        },
                        new
                        {
                            Id = 3,
                            Name = "gdrive",
                            Type = "cloud",
                            Url = "https://drive.google.com/drive/u/0/"
                        },
                        new
                        {
                            Id = 4,
                            Name = "gphotos",
                            Type = "cloud",
                            Url = "https://photos.google.com/?hl=es"
                        },
                        new
                        {
                            Id = 5,
                            Name = "youtube",
                            Type = "social",
                            Url = "https://www.youtube.com/"
                        },
                        new
                        {
                            Id = 6,
                            Name = "reddit",
                            Type = "social",
                            Url = "https://www.reddit.com/"
                        },
                        new
                        {
                            Id = 7,
                            Name = "twitch",
                            Type = "social",
                            Url = "https://www.twitch.tv/directory"
                        },
                        new
                        {
                            Id = 8,
                            Name = "twitter",
                            Type = "social",
                            Url = "https://www.twitter.com/"
                        },
                        new
                        {
                            Id = 9,
                            Name = "whatsapp",
                            Type = "social",
                            Url = "https://web.whatsapp.com/"
                        },
                        new
                        {
                            Id = 10,
                            Name = "fake email",
                            Type = "pirating",
                            Url = "https://temp-mail.org/"
                        },
                        new
                        {
                            Id = 11,
                            Name = "nyaa",
                            Type = "pirating",
                            Url = "https://nyaa.si/"
                        },
                        new
                        {
                            Id = 12,
                            Name = "rarbg",
                            Type = "pirating",
                            Url = "https://rargb.to/"
                        },
                        new
                        {
                            Id = 13,
                            Name = "fitgirl",
                            Type = "pirating",
                            Url = "http://fitgirl-repacks.site/"
                        },
                        new
                        {
                            Id = 14,
                            Name = "cs.rin.ru",
                            Type = "pirating",
                            Url = "https://cs.rin.ru"
                        },
                        new
                        {
                            Id = 15,
                            Name = "drive bypass",
                            Type = "pirating",
                            Url = "https://gdbypass.host/"
                        },
                        new
                        {
                            Id = 16,
                            Name = "r/piracy",
                            Type = "pirating",
                            Url = "https://www.reddit.com/r/Piracy/wiki/megathread"
                        },
                        new
                        {
                            Id = 17,
                            Name = "github",
                            Type = "services",
                            Url = "https://github.com/"
                        },
                        new
                        {
                            Id = 18,
                            Name = "bitbucket",
                            Type = "services",
                            Url = "https://bitbucket.com/"
                        },
                        new
                        {
                            Id = 19,
                            Name = "gmaps",
                            Type = "services",
                            Url = "https://www.google.com/maps"
                        },
                        new
                        {
                            Id = 20,
                            Name = "wetransfer",
                            Type = "services",
                            Url = "https://wetransfer.com/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
